spring:
  datasource:
    newdb: #配置数据源1:此处配置的mysql数据库  新库
      driverClassName: com.mysql.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://81.69.234.118:9200/day?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      type: com.alibaba.druid.pool.DruidDataSource
    historydb: #历史库
      #      jdbc-url: jdbc:postgresql://127.0.0.1:5432/test1
      #      username: postgres
      #      password: 123456
      #      driverClassName: org.postgresql.Driver
      #      #    platform: postgres
      #      type: com.alibaba.druid.pool.DruidDataSource
      #      initialization-mode: always
      driverClassName: com.mysql.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://81.69.234.118:9200/day2?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      type: com.alibaba.druid.pool.DruidDataSource

    # ============================== druid ============================== #
    druid:
      #最大活跃数
      maxActive: 20
      #初始化数量
      initialSize: 1
      #最大连接等待超时时间
      maxWait: 60000
      #打开PSCache，并且指定每个连接PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
      #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1 from dual
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
      filters: stat,wall
#      filters: stat,wall
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*