server:
  port: 8083

spring:
  applicaiton:
    name: redis-application

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0


